MagicMVC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using MagicMVC.Models;
using MagicMVC.Data;
using Newtonsoft.Json;

namespace MagicMVC.Controllers
{
    [Authorize(Roles = Constants.CustomerRole)]
    public class CustomerController : Controller
    {
        private readonly MagicMVCContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        Customer customer;
        Franchisee franchisee;
        String userID;


        public CustomerController(MagicMVCContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            customer = new Customer(_context);
            franchisee = new Franchisee(_context);
        }

        // GET: Customer
        public async Task<IActionResult> Index(string productName, string storeName)
        {
            if (string.IsNullOrWhiteSpace(storeName))
            {
                storeName = _context.Stores.First().Name;
            }
            var productQuery = _context.StoreInventory.Include(s => s.Product).Include(s => s.Store).Where(p => p.Store.Name == storeName);

            if (!string.IsNullOrWhiteSpace(productName))
            {
                // Get products matching the name given.
                productQuery = productQuery.Where(p => p.Product.Name.Contains(productName));

                // Storing the search into ViewBag to populate the textbox with the same value for convenience.
                ViewBag.ProductName = productName;
            }

            ViewData["StoreName"] = new SelectList(_context.Stores, "Name", "Name", storeName);
            
            return View(await productQuery.ToListAsync());
        }

        // GET: Customer/History
        public async Task<IActionResult> History()
        {
            var productQuery = _context.Orders
                .Where(o => o.CustomerID == _userManager.GetUserId(User));

            return View(await productQuery.ToListAsync());
        }

        // GET: Customer/Purchase/5
        public async Task<IActionResult> AddToCart(int ProductID, int id = 1)
        {
            userID = _userManager.GetUserId(User);
            var storeInventory = await _context.StoreInventory
                                    .Where(r => r.ProductID == ProductID)
                                     .SingleOrDefaultAsync(m => m.StoreID == id);

            if (storeInventory == null)
            {
                return NotFound();
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", storeInventory.ProductID);
            ViewData["StoreID"] = new SelectList(_context.Stores, "StoreID", "StoreID", storeInventory.StoreID);

            Purchase p = new Purchase { StoreID = id, ProductID = ProductID, QuantityToPurchase = 0, Confirmed = false, DateOfPurchase = DateTime.MinValue, CustomerID = userID}; 

            return View(p);
        }

        // POST: Customer/Purchase/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToCart(int id, [Bind("StoreID,ProductID,QuantityToPurchase,Confirmed,DateOfPurchase,CustomerID")] Purchase p)
        {
            p.CustomerID = _userManager.GetUserId(User);

            if (id != p.StoreID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                { 
                    franchisee.StoreID = id;
                    var numInStock = await franchisee.getStockLevel(p.ProductID);
                    if (numInStock < p.QuantityToPurchase)
                    {
                        //return View;
                        throw new Exception();
                    }
                    await customer.SaveToCart(p);
                }
                catch (DbUpdateConcurrencyException)
                {
                    bool inventoryExists = await franchisee.StoreInventoryExists(p.ProductID);
                    if (!inventoryExists)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", p.ProductID);
            ViewData["StoreID"] = new SelectList(_context.Stores, "StoreID", "StoreID", p.StoreID);
            return View(p);
        }
    }
}

MagicMVC/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MagicMVC.Models;
using MagicMVC.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;

namespace MagicMVC.Controllers
{

    // StoreController: Franchisee needs to see stock & be able to make stock requests
    [Authorize(Roles=Constants.FranchiseeRole)]
    public class StoreController : Controller
    {
        public const string SessionFranchiseStoreID = "_FranchiseStoreID";
        private readonly MagicMVCContext _context;
        private Store Store;
        private string UserID;

        public StoreController(MagicMVCContext context)
        {
            _context = context;
            
        }

        private void FetchStore()
        {
            var sessionID = HttpContext.Session.GetInt32(SessionFranchiseStoreID);
            var claimsIdentity = User.Identity as ClaimsIdentity;
            UserID = claimsIdentity.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;

            Store = _context.Stores
                        .Include(s => s.StoreInventoryList)
                        .FirstOrDefault(s => s.FranchiseeUser == UserID);
        }

        
        
        // GET: Unstocked Items - show items in Owner Inventory which Store does not have in stock.
        public async Task<IActionResult> Unstocked()
        {
            FetchStore();
            int storeID = Store.StoreID;
            Franchisee franchisee = new Franchisee(_context, UserID, storeID);

            // Load products in OwnerInventory that aren't in this Store's Inventory
            var storeInventory = await franchisee.GetStoreInventory();
            List<OwnerInventory> inventory = await _context.OwnerInventory.Include(i => i.Product).Where(o => !storeInventory.Any(s => s.ProductID == o.ProductID)).ToListAsync();

            //Passing a List<OwnerInventory> model object to the View.

            return View(inventory);
        }


        // GET: Store Index - shows inventory for the user's store.
        public async Task<IActionResult> Index(string productName, int threshold, int id = 1)
        {
            FetchStore();
            int storeID = Store.StoreID;

            Franchisee franchisee = new Franchisee(_context, UserID, storeID);
            
            List<StoreInventory> inventory = await franchisee.GetStoreInventory();
            
            // Eager loading the Product table - join between StoreInventory and the Product table.

            var productQuery = _context.StoreInventory.Include(x => x.Product).Where(p => p.StoreID == storeID);

            if (!string.IsNullOrWhiteSpace(productName))
            {
                inventory = await franchisee.GetStoreInventory(productName);
                
                // Storing the search into ViewBag to populate the textbox with the same value for convenience.
                ViewBag.ProductName = productName;
            }

            if (threshold != 0)
            {
                inventory = await franchisee.GetStoreInventoryBelowThreshold(threshold);

                // Storing the search into ViewBag to populate the textbox with the same value for convenience.
                ViewBag.Threshold = threshold;
            }

            //Passing a List<OwnerInventory> model object to the View.

            return View(inventory);
        }

        // GET: Store/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var storeInventory = await _context.StoreInventory
                .Include(s => s.Product)
                .Include(s => s.Store)
                .SingleOrDefaultAsync(m => m.StoreID == id);
            if (storeInventory == null)
            {
                return NotFound();
            }

            return View(storeInventory);
        }

        // GET: Store/MakeStockRequest
        public IActionResult MakeStockRequest(int? id)
        {
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", id ?? _context.Products.First().ProductID);
            return View();
        }

        // POST: Store/MakeStockRequest
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MakeStockRequest([Bind("StoreID,ProductID,Quantity")] StockRequest stockRequest)
        {
            if (ModelState.IsValid)
            {
                FetchStore();
                stockRequest.StoreID = Store.StoreID;
                _context.Add(stockRequest);

                // if this product wasn't previously in stock, add it to the store stock with quantity 1
                if (!Store.StoreInventoryList.Any(si => si.ProductID == stockRequest.ProductID)) {
                    _context.Add(new StoreInventory
                    {
                        StoreID = Store.StoreID,
                        Product = _context.Products.Find(stockRequest.ProductID),
                        StockLevel = 1
                    });
                }
                

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(stockRequest);
        }

        // GET: Store/Create
        public IActionResult Create()
        {
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID");
            ViewData["StoreID"] = new SelectList(_context.Stores, "StoreID", "StoreID");
            return View();
        }

        // POST: Store/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StoreID,ProductID,StockLevel")] StoreInventory storeInventory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(storeInventory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", storeInventory.ProductID);
            ViewData["StoreID"] = new SelectList(_context.Stores, "StoreID", "StoreID", storeInventory.StoreID);
            return View(storeInventory);
        }

        // GET: Store/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var storeInventory = await _context.StoreInventory.SingleOrDefaultAsync(m => m.StoreID == id);
            if (storeInventory == null)
            {
                return NotFound();
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", storeInventory.ProductID);
            ViewData["StoreID"] = new SelectList(_context.Stores, "StoreID", "StoreID", storeInventory.StoreID);
            return View(storeInventory);
        }

        // POST: Store/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StoreID,ProductID,StockLevel")] StoreInventory storeInventory)
        {
            if (id != storeInventory.StoreID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(storeInventory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoreInventoryExists(storeInventory.StoreID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", storeInventory.ProductID);
            ViewData["StoreID"] = new SelectList(_context.Stores, "StoreID", "StoreID", storeInventory.StoreID);
            return View(storeInventory);
        }

        // GET: Store/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var storeInventory = await _context.StoreInventory
                .Include(s => s.Product)
                .Include(s => s.Store)
                .SingleOrDefaultAsync(m => m.StoreID == id);
            if (storeInventory == null)
            {
                return NotFound();
            }

            return View(storeInventory);
        }

        // POST: Store/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var storeInventory = await _context.StoreInventory.SingleOrDefaultAsync(m => m.StoreID == id);
            _context.StoreInventory.Remove(storeInventory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

MagicMVC/Views/Shared/_HeadNavBar.cshtml
@using MagicMVC.Data;
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Melbourne Magic</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (User.IsInRole(Constants.OwnerRole))
                    {
                        <li><a asp-area="" asp-controller="OwnerInventory" asp-action="Index">Owner Inventory</a></li>
                        <li><a asp-area="" asp-controller="StockRequests" asp-action="Index">View Stock Requests</a></li>
                    }

                    @if (User.IsInRole(Constants.FranchiseeRole))
                    {

                        <li><a asp-area="" asp-controller="Store" asp-action="Index">Store Inventory</a></li>
                    }

                    @if (User.IsInRole(Constants.CustomerRole))
                    {
                        <li><a asp-area="" asp-controller="Customer" asp-action="Index">Browse Products</a></li>
                        <li><a asp-area="" asp-controller="ShoppingCart" asp-action="Index">Your Cart</a></li>
                        <li><a asp-area="" asp-controller="Customer" asp-action="History">Your Order History</a></li>
                    }

                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>

MagicMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Melbourne Magic</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @await Html.PartialAsync("_HeadNavBar")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Melbourne Magic</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>